apiVersion: v1
kind: Service
metadata:
    name: "vienaks"
    labels:
        app: "vienaks"
spec:
    type: LoadBalancer
    ports:
    - port: 3310
      targetPort: http
      protocol: TCP
      name: http
    selector:
        app: "vienaks"